#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

ninslash_stats_ - Wildcard plugin to monitor the amount of active players on OpenArena servers

=head1 CONFIGURATION

This is a wildcard plugin. It requires running munin-node-configure periodically.

Copy this file to /usr/share/munin/plugins

Put this line to your root crontab, using 'sudo crontab -e':

0-59/2 * * * * /usr/sbin/munin-node-configure --shell --remove-also 2>/dev/null | grep -E 'oa_stats_|ninslash_stats_' | sh

Also edit file /etc/cron.d/munin to increase data collection rate for munin-cron from 5 to 2 minutes.

This plugin uses environment variable QSTAT_PATH, which is set to /home/oa/qstat by default.

=head1 USAGE

---

=head1 AUTHOR

Unknown author

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf suggest

=cut

. $MUNIN_LIBDIR/plugins/plugin.sh

SERVER=${0##*/ninslash_stats_}
LOG=/run/shm/ninslash-stats.log
[ -z "$QSTAT_PATH" ] && QSTAT_PATH=/home/oa/qstat

if [ "$1" = "autoconf" ]; then
    echo yes
    exit 0
fi

if [ "$1" = "suggest" ]; then
    ( cd $QSTAT_PATH ; ./tw_api.py > $LOG.tmp ; mv -f $LOG.tmp $LOG ; )
    [ -e $LOG ] || exit 1
    cat $LOG | cut -s -d ' ' -f 1
    exit 0
fi

NAME="`cat $LOG | grep -F $SERVER\  | cut -s -d ' ' -f 8-`"
[ -z "$NAME" ] && exit 1
PLAYERS_ACTIVE="`cat $LOG | grep -F $SERVER\  | cut -s -d ' ' -f 3`"
PLAYERS_MAX="`cat $LOG | grep -F $SERVER\  | cut -s -d ' ' -f 4`"

# echo "players - $PLAYERS -- $PLAYERS_ACTIVE --- $PLAYERS_MAX ----"

if [ "$1" = "config" ]; then
    echo "graph_title $NAME - $SERVER"
    echo "graph_args --base 1000 --lower-limit 0" # --upper-limit $PLAYERS_MAX
    echo 'graph_vlabel Active players'
    echo 'graph_category ninslash'
    echo "graph_info This graph shows the amount of active players on server $NAME - $SERVER"
    echo 'players.label players'
    echo 'players.info Amount of active players'
    echo 'graph_data_size custom 2m for 1d, 2m for 1w, 4m for 1t, 16m for 1y'
    #echo 'graph_data_size huge'
    echo 'update_rate 120'
    #echo 'players.type GAUGE'
    exit 0
fi;

echo "players.value $PLAYERS_ACTIVE"
exit 0
