#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

oa_stats_ - Wildcard plugin to monitor the amount of active players on OpenArena servers

=head1 CONFIGURATION

This is a wildcard plugin. It requires running munin-node-configure periodically.

Copy this file to /usr/share/munin/plugins

Put this line to your root crontab, using 'sudo crontab -e':

0-59/5 * * * * /usr/sbin/munin-node-configure --shell --remove-also 2>/dev/null | grep -E 'oa_stats_|ninslash_stats_' | sh

This plugin uses environment variable QSTAT_PATH, which is set to /home/oa/qstat by default.

=head1 USAGE

---

=head1 AUTHOR

Unknown author

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf suggest

=cut

. $MUNIN_LIBDIR/plugins/plugin.sh

SERVER=${0##*/oa_stats_}
LOG=/run/shm/qstat.log
[ -z "$QSTAT_PATH" ] && QSTAT_PATH=/home/oa/qstat

if [ "$1" = "autoconf" ]; then
    echo yes
    exit 0
fi

if [ "$1" = "suggest" ]; then
    rm -f $LOG
    ( cd $QSTAT_PATH ; ./qstat -sort g -cfg qstat.cfg -oaam dpmaster.deathmask.net:27950 | grep '^OAAS' | tr -s ' ' > $LOG ; )
    [ -e $LOG ] || exit 1
    cat $LOG | cut -s -d ' ' -f 2
    exit 0
fi

NAME="`cat $LOG | grep -F OAAS\ $SERVER\  | cut -s -d ' ' -f 10-`"
[ -z "$NAME" ] && exit 1
PLAYERS="`cat $LOG | grep -F OAAS\ $SERVER\  | cut -s -d ' ' -f 3`"
PLAYERS_ACTIVE="`echo $PLAYERS | sed 's@/[0-9]*@@'`"
PLAYERS_MAX="`echo $PLAYERS | sed 's@[0-9]*/@@'`"

# echo "players - $PLAYERS -- $PLAYERS_ACTIVE --- $PLAYERS_MAX ----"

if [ "$1" = "config" ]; then
    echo "graph_order players"
    echo "graph_title $NAME - $SERVER"
    echo "graph_args --base 1000 --lower_limit 0 --upper_limit $PLAYERS_MAX"
    echo 'graph_vlabel Active players'
    echo 'graph_category OpenArena'
    echo "graph_info This graph shows the amount of active players on server $NAME $SERVER"
    echo 'players.label Players'
    echo 'players.type GAUGE'
    exit 0
fi;

echo "players.value $PLAYERS_ACTIVE"
exit 0
