#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

openlierox_stats_ - Wildcard plugin to monitor the amount of active players on OpenLieroX servers

=head1 CONFIGURATION

This is a wildcard plugin. It requires running munin-node-configure periodically.

Copy this file to /usr/share/munin/plugins

Run:

sudo munin-node-configure --shell | grep -E 'openlierox_stats_' | sudo sh
sudo chown root:munin /etc/munin/plugins
sudo chmod 775 /etc/munin/plugins

Edit file /etc/cron.d/munin to increase data collection rate for munin-cron from 5 to 1 minute:

* * * * *     munin if [ -x /usr/bin/munin-cron ]; then /usr/bin/munin-cron; fi

Enable 'graph_strategy cgi' in Munin, as described here: https://wiki.debian.org/Munin/ApacheConfiguration

This plugin uses environment variable QSTAT_PATH, which is set to /home/oa/qstat by default.

=head1 USAGE

---

=head1 AUTHOR

Sergii Pylypenko

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf suggest

=cut

. $MUNIN_LIBDIR/plugins/plugin.sh

SERVER=${0##*/openlierox_stats_}
LOG=/run/shm/openlierox.log
[ -z "$QSTAT_PATH" ] && QSTAT_PATH=/home/oa/qstat

if [ "$1" = "autoconf" ]; then
    echo yes
    exit 0
fi

if [ "$1" = "suggest" ]; then
    echo ".master"
    exit 0
fi

if [ "$SERVER" = ".master" ]; then

    if [ "$1" = "config" ]; then
        echo "graph_title $SERVER"
        echo "graph_args --base 1000 --lower-limit 0 --upper-limit 16"
        echo 'graph_vlabel Servers'
        echo 'graph_category openlierox'
        echo "graph_info This graph shows the amount of servers registered on master"
        echo 'servers.label servers'
        echo 'servers.info Amount of servers'
        echo 'graph_data_size huge'
        echo 'update_rate 60'
        #echo 'players.type GAUGE'
        exit 0
    fi

    ( cd $QSTAT_PATH ; ./qstat -sort g -cfg qstat.cfg -olxm server.az2000.de:23450 | grep '^OLXS' | tr -s ' ' | grep -v ' no response$' > $LOG.tmp ; mv -f $LOG.tmp $LOG ; )

    SERVERS_ACTIVE="`cat $LOG | wc -l`"

    echo "servers.value $SERVERS_ACTIVE"

    RESTART=false
    for f in `cat $LOG | cut -s -d ' ' -f 2`; do
        if [ -e "/etc/munin/plugins/openlierox_stats_$f" ]; then true; else
            RESTART=true
            ln -s -f "$0" "/etc/munin/plugins/openlierox_stats_$f"
        fi
    done

    if $RESTART; then
        true
        # systemctl restart munin-node # Cannot do because of no permissions
    fi

    exit 0
fi

NAME="`cat $LOG | grep -F OLXS\ $SERVER\  | cut -s -d ' ' -f 8- | tr \"'\" \" \"`"
[ -z "$NAME" ] && exit 1
PLAYERS="`cat $LOG | grep -F OLXS\ $SERVER\  | cut -s -d ' ' -f 3`"
PLAYERS_ACTIVE="`echo $PLAYERS | sed 's@/[0-9]*@@'`"
PLAYERS_MAX="`echo $PLAYERS | sed 's@[0-9]*/@@'`"

#echo "players - $PLAYERS -- $PLAYERS_ACTIVE --- $PLAYERS_MAX ----"

if [ "$1" = "config" ]; then
    echo "graph_title $NAME - $SERVER"
    echo "graph_args --base 1000 --lower-limit -1 --upper-limit 16 --rigid" # --upper-limit $PLAYERS_MAX
    echo 'graph_vlabel Active players'
    echo 'graph_category openlierox'
    echo "graph_info This graph shows the amount of active players on server $NAME $SERVER"
    echo 'players.label players'
    echo 'players.info Amount of active players'
    #echo 'graph_data_size custom 30d, 1m for 1w, 1m for 1t, 16m for 1y'
    echo 'graph_data_size huge'
    echo 'update_rate 60'
    #echo 'players.type GAUGE'
    exit 0
fi;

echo "players.value $PLAYERS_ACTIVE"

exit 0
